language: node_js
node_js: node
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts: github.com
install:
- npm install
script:
- hexo g
deploy:
  provider: script
  script: ".travis/deploy.sh"
  skip_cleanup: true
  on:
    branch: source
